env:
  browser: true
  commonjs: true
  es6: true
  webextensions: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2017
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never
